from setuptools import setup

setup(
    name='radiusTest',
    version='1.0',
    packages=['venv.lib.python3.6.site-packages.cffi', 'venv.lib.python3.6.site-packages.idna',
              'venv.lib.python3.6.site-packages.yaml', 'venv.lib.python3.6.site-packages.click',
              'venv.lib.python3.6.site-packages.flask', 'venv.lib.python3.6.site-packages.flask.ext',
              'venv.lib.python3.6.site-packages.pyrad', 'venv.lib.python3.6.site-packages.pyrad.tests',
              'venv.lib.python3.6.site-packages.jinja2', 'venv.lib.python3.6.site-packages.netaddr',
              'venv.lib.python3.6.site-packages.netaddr.ip', 'venv.lib.python3.6.site-packages.netaddr.eui',
              'venv.lib.python3.6.site-packages.netaddr.contrib', 'venv.lib.python3.6.site-packages.netaddr.strategy',
              'venv.lib.python3.6.site-packages.OpenSSL', 'venv.lib.python3.6.site-packages.dateutil',
              'venv.lib.python3.6.site-packages.dateutil.tz', 'venv.lib.python3.6.site-packages.dateutil.parser',
              'venv.lib.python3.6.site-packages.dateutil.zoneinfo', 'venv.lib.python3.6.site-packages.werkzeug',
              'venv.lib.python3.6.site-packages.werkzeug.debug', 'venv.lib.python3.6.site-packages.werkzeug.contrib',
              'venv.lib.python3.6.site-packages.aniso8601', 'venv.lib.python3.6.site-packages.flask_ask',
              'venv.lib.python3.6.site-packages.pycparser', 'venv.lib.python3.6.site-packages.pycparser.ply',
              'venv.lib.python3.6.site-packages.asn1crypto', 'venv.lib.python3.6.site-packages.asn1crypto._perf',
              'venv.lib.python3.6.site-packages.markupsafe', 'venv.lib.python3.6.site-packages.cryptography',
              'venv.lib.python3.6.site-packages.cryptography.x509',
              'venv.lib.python3.6.site-packages.cryptography.hazmat',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.backends',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.backends.openssl',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.bindings',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.bindings.openssl',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.kdf',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.ciphers',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.twofactor',
              'venv.lib.python3.6.site-packages.cryptography.hazmat.primitives.asymmetric',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'venv.lib.python3.6.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='MIT',
    author='themooer1',
    author_email='fluffy1781@gmail.com',
    description='RADIUS server, which generates tokens using Alexa.'
)
